#!/bin/sh

#设置中文
uci set luci.main.lang=zh_cn
uci commit luci
#设置时区、ntp服务器
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai

uci delete system.ntp
uci set system.ntp='timeserver'
#uci set system.ntp.use_dhcp='0'
uci add_list system.ntp.server='ntp.aliyun.com'
uci add_list system.ntp.server='time1.cloud.tencent.com'
uci add_list system.ntp.server='time.ustc.edu.cn'
uci add_list system.ntp.server='cn.pool.ntp.org'
uci commit system

#修改路由器登录地址为192.168.50.1
uci set network.lan.ipaddr='192.168.50.1'
uci commit network

uci set network.wan.proto='pppoe'
uci set network.wan.peerdns='0'
uci add_list network.wan.dns='119.29.29.29'
uci add_list network.wan.dns='223.5.5.5'
uci commit network

echo -n "net.ipv4.tcp_fastopen = 3" >> /etc/sysctl.conf

#创建自己的防火墙表user
echo 'nft delete table ip user' >>/etc/firewall.user
echo 'nft add table ip user' >>/etc/firewall.user
echo 'nft add chain ip user input { type filter hook input priority 0 \; policy accept \; }' >>/etc/firewall.user 
echo 'nft add chain ip user FORWARD { type filter hook forward priority 0 \; policy accept \; }' >>/etc/firewall.user
#劫持53端口流量，由路由器处理，科学上网更稳定
echo 'nft add chain ip user PREROUTING { type nat hook prerouting priority dstnat \; policy accept \; }' >>/etc/firewall.user
echo 'nft add rule ip user PREROUTING tcp dport 53 counter redirect to :53' >>/etc/firewall.user
echo 'nft add rule ip user PREROUTING udp dport 53 counter redirect to :53' >>/etc/firewall.user
#下面自定义防火墙规则
#echo 'nft insert rule ip user FORWARD ip daddr 192.168.1.209 meta hour "12:00"-"13:10" counter drop' >>/etc/firewall.user
#echo 'nft insert rule ip user FORWARD ip daddr 192.168.1.203 meta hour "01:00"-"18:05" counter drop' >>/etc/firewall.user
#echo 'nft insert rule ip user FORWARD ip daddr 192.168.1.203 meta hour "22:05"-"23:55" counter drop' >>/etc/firewall.user
#echo 'nft insert rule ip user FORWARD ip daddr 192.168.1.218 meta hour "02:00"-"23:55" counter drop' >>/etc/firewall.user
#让防火墙调用script
uci set firewall.userfirewall='include'
uci set firewall.@include[-1].type="script"
uci set firewall.@include[-1].path="/etc/firewall.user"
uci set firewall.@include[-1].fw4_compatible="1"
uci commit firewall
/etc/init.d/firewall restart


exit 0
